algoritmo "AcumuladorOuSomador"
  //Esse algoritmo efetua a soma de 4 números
var
soma, n: inteiro

inicio
   soma <- 0
   Escreva("Digite o 1°numero:")
   leia(n)
   soma <-soma + n

   Escreva("Digite o 2° número:")
   leia(n)
   soma <- soma + n

   Escreva("Digite o 3° número:")
   leia(n)
   soma <- soma + n

   Escreva("Digite o 4° número:")
   leia(n)
   soma <- soma + n


   Escreval("A soma dos números é: " , soma)

fimalgoritmo
